controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/auth/login
    methods: [POST]

api_token_refresh:
    path: /api/token/refresh
    methods: [POST]
